// Scrapes the full undergraduate course index from the USask catalogue into src/data/courses.ts,
// the list the course search box matches against.
// Run: node --experimental-strip-types scripts/scrape-courses.ts
//
// This is deliberately separate from scrape-prereqs.ts: that one carries prerequisite chains for
// the ~240 courses the planner actually reasons about, this one carries code + title for every
// course a student could plausibly have on a transcript. Different jobs, different sizes.
import { writeFileSync } from 'node:fs'
import { parseSubjectPage } from './scrape-prereqs.ts'

const SUBJECT_LIST = 'https://catalogue.usask.ca/'
const SEARCH = 'https://catalogue.usask.ca/?subj_code=$SUBJ&cnum=%25'

/** Graduate courses (800+) never appear on an undergraduate transcript. */
const MAX_COURSE_NUMBER = 500

async function subjectCodes(): Promise<string[]> {
  const html = await (await fetch(SUBJECT_LIST)).text()
  const options = [...html.matchAll(/<option value="([A-Z]{2,5})"/g)].map((m) => m[1])
  return [...new Set(options)].sort()
}

async function main() {
  const subjects = await subjectCodes()
  console.log(`${subjects.length} subject codes`)

  const rows: string[] = []
  let scanned = 0

  for (const subject of subjects) {
    const res = await fetch(SEARCH.replace('$SUBJ', subject))
    if (!res.ok) {
      console.warn(`${subject}: HTTP ${res.status} — skipped`)
      continue
    }
    const courses = parseSubjectPage(await res.text(), subject)
    scanned += courses.length

    for (const course of courses) {
      const number = Number(course.code.replace(/^[A-Z]+/, ''))
      if (number >= MAX_COURSE_NUMBER) continue
      // Pipe-delimited so the generated file stays a single string literal rather than 10k object
      // literals — same data, a fraction of the bundle.
      if (course.title.includes('|')) continue
      rows.push(`${course.code}|${course.title}`)
    }
  }

  rows.sort()

  const file =
    `// GENERATED by scripts/scrape-courses.ts from catalogue.usask.ca on ${new Date().toISOString().slice(0, 10)}.\n` +
    `// Do not edit by hand — rerun the scraper instead.\n` +
    `//\n` +
    `// Every undergraduate course (below ${MAX_COURSE_NUMBER}) in the catalogue, as "CODE|Title" lines.\n` +
    `// Stored as one string and split at load: 10k object literals would cost several times this in\n` +
    `// bundle size for identical data.\n\n` +
    `export interface CatalogueCourse {\n  code: string\n  title: string\n}\n\n` +
    `const RAW = \`${rows.join('\n')}\`\n\n` +
    `export const catalogueCourses: CatalogueCourse[] = RAW.split('\\n').map((line) => {\n` +
    `  const [code, title] = line.split('|')\n` +
    `  return { code, title }\n` +
    `})\n`

  writeFileSync(new URL('../src/data/courses.ts', import.meta.url), file)
  console.log(`Wrote src/data/courses.ts — ${rows.length} undergraduate courses (${scanned} scanned).`)
}

await main()
